version: '3.8'
services:
  carla-server:
    image: carlasim/carla:0.9.13
    runtime: nvidia
    network_mode: host
    environment:
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
    command: bash CarlaUE4.sh -nosound

  ros-client:
    image: goldfish1295/carla_ros_client:0.9.13-foxy
    depends_on:
      - carla-server
    network_mode: host
    environment:
      - ROS_DOMAIN_ID=1
    volumes:
      - ../:/root/ros2_ws:rw
    working_dir: /root/ros2_ws
    stdin_open: true
    tty: true